# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        news:
            uri_prefix: /images/news
            upload_destination: '%kernel.project_dir%/public/images/news'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer